name: Enforce PR labels

on:
  pull_request:
    branches:
      - "!dependabot/**"
    types:
      - labeled
      - unlabeled
      - opened
      - reopened
      - synchronize

# This ensures that previous jobs for the workflow are canceled when the ref is
# updated.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  enforce-labels:
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - uses: Onemind-Services-LLC/actions-pr-label-enforcer@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          regex: "type: *"
